### ISSUE TITLE
templated simd constructor

### ISSUE THREAD

**Issue by mperrinel** [NexGenAnalytics/simd-math#5]
One of the simd constructor is templated but the template doesn't seem to be used:
```
template <class Flags>
  SIMD_ALWAYS_INLINE inline simd(double const* ptr, Flags /*flags*/)
    :m_value(_mm_loadu_pd(ptr))
  {}
```
What is the meaning for "Flags" here ?
Can we simply remove it ?

**Comment by fnrizzi** [comment]
opened it in https://github.com/kokkos/simd-math/issues/30
